[book]
title = "NINA's data management handbook"
description = " "
authors = ["Benjamin Cretois", "Francesco Frassinelli", "Matthew Grainger"]
language = "en"

[rust]
edition = "2021"

[output.html]
mathjax-support = true
site-url = "/mdBook/"
git-repository-url = "https://github.com/NINAnor/data-management-handbook"
edit-url-template = "https://github.com/NINAnor/data-management-handbook/edit/main/{path}"
additional-js = ["mermaid.min.js", "mermaid-init.js"]

[output.html.playground]
editable = true
line-numbers = true

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2

[output.html.redirect]
"/format/config.html" = "configuration/index.html"

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"
